### ISSUE TITLE
Report page - Side menu

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#121]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
When the side menu is hidden, the component transforms into a vertical rectangle with no information about what's available on it. Even if the component is collapsed, it should include an icon or something to indicate what's within.

**Steps to reproduce: ❗️**
1. Click the arrow button to hide the component.

**Screenshots or Video**
<img width="529" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/7cc1c9fb-9e00-4bd6-b9e3-b81267ac008f">
<img width="280" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/8f1122fd-5c47-4825-b233-38fff48cc9a9">

**Expected behavior:  ❗️**
When hidden, display an icon with a description of the content.

**Actual behavior:  ❗️**
When hidden becomes white.

**Additional context:**
This bug should be fixed in design first. This is a design issue:
<img width="183" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/f3e71509-31f1-4e3e-9756-88d539364326"> 

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @rjung07 ,

Please let me know once the design team finalized this.

CC: @StephanyJade

**Comment by rjung07** [comment]
Hi @StephanyJade and @Haidoe my suggestions are:

I guess this one looks weird because of the shading on the button.
![image](https://github.com/Haidoe/arc/assets/123789857/9e3c7175-eef6-48c4-b5f9-0a9fb63be7db)

We could also do like this, but also looks a little crowded.
![image](https://github.com/Haidoe/arc/assets/123789857/12225961-0d24-4ae3-acd9-224cf36f1f10)

One second option would be to have a wider width for this and use text.
Will check with the designers after class today.

**Comment by rafaelajung** [comment]
@Haidoe and @jbsinluenam 
Please follow this option.

![image](https://github.com/Haidoe/arc/assets/123789857/04aea253-b639-4171-b881-9cbaa39419aa)

**Comment by Haidoe** [comment]
duplicate issue 

https://github.com/Haidoe/arc/issues/128
