### ISSUE TITLE
Dashboard: Production progress chart colors

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#277]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
Colors based on the Mock up are not aligned.

**Screenshots or Video**
<img width="997" alt="Screen Shot 2023-07-31 at 9 07 28 PM" src="https://github.com/Haidoe/arc/assets/123606372/a9f1b675-c20e-4d38-803e-27505c364b8e">

**Expected behavior:  ❗️**
Gradient with a purple ba
<img width="819" alt="Screen Shot 2023-07-31 at 9 06 33 PM" src="https://github.com/Haidoe/arc/assets/123606372/59a99ccd-a9fc-4935-bcb6-afe1fb405ba7">
se should be the color of the meter.

**Actual behavior:  ❗️**
Only solid colors are visible.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@kbmirambel it's difficult to achieve the gradient functionality if the the bar is filled by small portion. You'll see it only if the bar is filled by half.
Therefore the idea of Legend colors to Blueish color was implemented, because doing it the way as shown in the figma always displayed blue.

Although the Legends were made solid colors for accessbility. This could be implemented as done in figma. Do you want to make legends gradients as well or leave them solid?

**Comment by kbmirambel** [comment]
@ksdhir that's understandable. Thank you for making it clear to me, appreciate it. and yes I find his implementation to be precisely what I had envisioned.
